export {
  buildUnitPriceBreakdown,
  calculateAnnualElectricityCost,
  calculateIndustryElectricity,
  getBenchmarkComparison,
  getReductionPotential,
} from "./industryElectricityCalc";
export {
  baseChargeEquivalentMap,
  buildingBaseUnitPriceMap,
  contractFactorMap,
  fuelAdjustmentByRegion,
  INDUSTRY_BENCHMARK_TOP25_MULTIPLIER,
  PRICE_RANGE_HIGH_MULTIPLIER,
  PRICE_RANGE_LOW_MULTIPLIER,
  reductionRateMap,
  regionFactorMap,
  RENEWABLE_SURCHARGE_PER_KWH,
  scaleDefaultMonthlyKwhMap,
  scaleFactorMap,
} from "./unitPriceMatrix";
export type {
  AnnualCostRange,
  BenchmarkComparison,
  BuildingType,
  ContractType,
  IndustryCalculatorInput,
  IndustryCalculatorResult,
  ReductionCase,
  ReductionCaseKind,
  ReductionPotential,
  Region,
  ScaleType,
  UnitPriceBreakdown,
  UsagePattern,
} from "./types";
